project:
  type: website
  output-dir: docs


website:
  title: "(Y): But Why?"
  site-url: https://tr1kar.github.io/
  description: 'Blog about understanding data and data science'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Tr1kar
      - icon: linkedin
        href: https://www.linkedin.com/in/alexraman92/


format:
  html:
    theme: theme.scss

comments:
  giscus:
    repo: Tr1kat/Tr1kar.github.io
