project:
  type: website


website:
  title: "(Y): but why?"
  site-url: ''
  description: 'Blog about understanding data and data science'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com


format:
  html:
    theme: theme.scss

