---
title: "Why am I writing this blog"
author: "Aleksandr Ramaniuk"
date: "2024-04-12"
categories: [personal]
---

```
Hello, world!
```

Based on [the](https://www.youtube.com/watch?v=gGxe2mN3kAg) [multiple](https://medium.com/@racheltho/why-you-yes-you-should-blog-7d2544ac1045) [suggestions](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html), I've decided to start my own blog. To be more exact, to start my blog here - I tried to write about my thoughts [long time ago](https://whiteraven1906.blogspot.com/).

#### Who am I?

First of all, who am I? My name is Alex, and I'm a self-described "person of broad interests"

- I'm a physicist. I got my PhD in theoretical physics, specifically nonlinear optics. I specialize in nonlinear fiber optics, but my interests include photonics, nonlinear optics, quantum optics, nanotechnology and much-much more.
- I'm a data scientist. I'm currently re-qualifying to become machine learning engineer and/or data scientist.
- I'm a storyteller. I have a dream of becoming a screenwriter or narrative designer. So far, my creative will goes into my 10+ years of experience with tabletop RPGs, as player and gamemaster.
- I'm an explorer of mind. I am interested in psychology, philosophy and different manners of self-development. I've been through coaching, therapy, ADHD diagnosis - and I've come out feeling much better afterwards.

As you can see, topics of this blog have a potential to be all over the place. It's ok. This is how I feel. If you feel lost - don't worry, use navigation tags.

#### So. Why am I writing this blog?

1. To structure my own mind.

I have many structures for my mind. I'm a kind of a... structuring enthusiast. I have bullet journal for calendar tasks, personal diary in OneNote, two whiteboards in my apartment, personal library in Qiqqa, GitHub repo, notes saved on two hard drives... Do I need more structure? 

Yes. Because it's one thing to have a thought in your mind. Other thing is to write it down. And another thing is to communicate it to someone else. Which leads to...

2. To re-learn and solidify knowledge

Programmers call it "rubber duck method". Physicists call it "Feynman method". Pedagogists call it "learning by teaching". The idea is all the same. The best way to check whether you understand something is to try and teach someone else. This also helps to...

3. To train my writing skills

As long as I remember myself, I was much better at oral communication than in written one. There is non-verbal context, there are gestures and facial expressions, there is mirroring and adjusting to the listeners... It's time to change that, through practice. Once I do it, I can...

4. To create my portfolio

Portfolio for what? I don't know. Maybe I can show some projects for data science applications. Maybe I have some ideas for writing gigs. Maybe I become an educator, and this is what I'll show. We'll see.

Most important of all, why do this (kind of) publicly?

5. **To help someone**

> You are best positioned to help people one step behind you.

This quote really stuck with me. I guess, I feel some kind of personal responsibility. I want to share what I know. Not to promote it - I don't have that much of an ego or self-esteem. But if at least someone finds what I write helpful...

That would be great.